"""Generator for the idempotent `auth setup` bash script.

This module is **pure** — it has no Proxmox or SSH dependencies — so the script
text can be unit-tested and previewed with `--dry-run` without any cluster.

The generated script runs on a PVE node as ``root@pam`` and:

1. Creates (or syncs) the proxcli custom roles with their privilege sets.
2. Creates an API token for the given user — or regenerates its secret —
   capturing the one-time secret via ``pvesh ... --output-format json``.
3. Binds each role to the token on the right ACL path.

It communicates structured results back to the caller by printing lines of the
form ``PROXCLI:<EVENT>:<args>`` on stdout.  The caller (see :mod:`proxmox.ssh.runner`)
parses these into a :class:`~proxmox.ssh.runner.SetupResult`.
"""

from __future__ import annotations

from dataclasses import dataclass, field


def _sh(value: str) -> str:
    """Single-quote ``value`` for safe interpolation into a bash script.

    Handles embedded single quotes via the standard ``'"'"'`` idiom.
    """
    return "'" + value.replace("'", "'\"'\"'") + "'"


@dataclass(frozen=True)
class SetupSpec:
    """Inputs for the generated setup script.

    Attributes:
        pve_user: Proxmox user the token is created for, e.g. ``root@pam``.
        token_name: Token ID, e.g. ``proxcli``.
        privsep: If True (default) the token gets *separated* privileges
            (effective perms = token ACLs only). If False the token inherits
            the full privileges of the user.
        regenerate: If True and the token already exists, rotate its secret.
            If False and the token exists, report ``TOKEN_EXISTS`` (the secret
            cannot be recovered — Proxmox stores it once).
        roles: Mapping of role name -> privilege string (comma-separated).
        acls: Ordered list of ``(path, role)`` pairs to bind the token to.
    """

    pve_user: str
    token_name: str
    privsep: bool = True
    regenerate: bool = False
    roles: dict[str, str] = field(default_factory=dict)
    acls: list[tuple[str, str]] = field(default_factory=list)


def generate_setup_script(spec: SetupSpec) -> str:
    """Return the bash setup script for the given :class:`SetupSpec`.

    The script is idempotent and safe to re-run. It requires ``root@pam`` on a
    PVE node (``pveum``/``pvesh`` only work as root).
    """
    if not spec.pve_user or not spec.token_name:
        raise ValueError("pve_user and token_name are required")
    if not spec.roles:
        raise ValueError("at least one role is required")

    lines: list[str] = []
    a = lines.append

    a("#!/usr/bin/env bash")
    a("# Generated by `proxmox auth setup --via ssh`.")
    a("# Creates the proxcli roles, an API token, and ACLs on this PVE host.")
    a("# Idempotent: safe to re-run. Requires root@pam (pveum/pvesh need root).")
    a("set -uo pipefail")
    a("")
    a(f"PVE_USER={_sh(spec.pve_user)}")
    a(f"TOKEN={_sh(spec.token_name)}")
    a(f"PRIVSEP={_sh('1' if spec.privsep else '0')}")
    a(f"REGENERATE={_sh('1' if spec.regenerate else '0')}")
    a('UG="${PVE_USER}!${TOKEN}"')
    a("")
    a('# Emit a parseable result line consumed by proxcli.')
    a('ok() { printf "PROXCLI:%s\\n" "$1"; }')
    a("")
    a('# Extract the token "value" field from pvesh JSON output.')
    a('# Handles both {"value":"..."} and the wrapped {"data":{"value":"..."}}.')
    a('_extract_secret() {')
    a('  local out="$1" sec')
    a('  sec=$(printf \'%s\' "$out" | python3 -c "')
    a("    import sys, json")
    a("    d = json.load(sys.stdin)")
    a("    v = d.get('value') if isinstance(d, dict) else None")
    a("    if v is None and isinstance(d, dict):")
    a("        v = (d.get('data') or {}).get('value')")
    a("    print(v or '')")
    a('  " 2>/dev/null) || true')
    a('  if [ -z "$sec" ]; then')
    a('    # grep fallback if python3 is unavailable')
    a('    sec=$(printf \'%s\' "$out" \\')
    a('      | grep -oE \'"value"[[:space:]]*:[[:space:]]*"[^"]+"\' \\')
    a('      | head -1 \\')
    a('      | sed -E \'s/.*"value"[[:space:]]*:[[:space:]]*"([^"]+)".*/\\1/\')')
    a('  fi')
    a('  printf \'%s\' "$sec"')
    a("}")
    a("")
    a("# ---- Roles (idempotent: create or sync privileges) ----")
    a("role_ensure() {")
    a('  local name="$1" privs="$2"')
    a('  if pveum role list 2>/dev/null | grep -qw "$name"; then')
    a('    if pveum role modify "$name" --privs "$privs" >/dev/null 2>&1; then')
    a('      ok "ROLE_UPDATED:${name}"')
    a("    else")
    a('      ok "ROLE_UPDATE_FAILED:${name}"')
    a("    fi")
    a("  else")
    a('    if pveum role add "$name" --privs "$privs" >/dev/null 2>&1; then')
    a('      ok "ROLE_CREATED:${name}"')
    a("    else")
    a('      ok "ROLE_CREATE_FAILED:${name}"')
    a("    fi")
    a("  fi")
    a("}")
    a("")
    for role_name, privs in spec.roles.items():
        a(f'role_ensure {_sh(role_name)} {_sh(privs)}')
    a("")
    a("# ---- API token ----")
    a('TOKEN_PATH="/access/users/${PVE_USER}/token/${TOKEN}"')
    a('if pvesh get "$TOKEN_PATH" >/dev/null 2>&1; then')
    a('  if [ "$REGENERATE" = "1" ]; then')
    a('    OUT=$(pvesh set "$TOKEN_PATH" --regenerate 1 --output-format json 2>/dev/null) || true')
    a('    SECRET=$(_extract_secret "$OUT")')
    a('    if [ -n "$SECRET" ]; then')
    a('      ok "TOKEN_REGENERATED:${UG}"; ok "TOKEN_SECRET:${SECRET}"')
    a("    else")
    a('      ok "TOKEN_REGEN_FAILED:${UG}"')
    a("    fi")
    a("  else")
    a('    ok "TOKEN_EXISTS:${UG}"')
    a("  fi")
    a("else")
    a('  OUT=$(pvesh create "$TOKEN_PATH" --privsep "$PRIVSEP" --output-format json 2>/dev/null) || true')
    a('  SECRET=$(_extract_secret "$OUT")')
    a('  if [ -n "$SECRET" ]; then')
    a('    ok "TOKEN_CREATED:${UG}"; ok "TOKEN_SECRET:${SECRET}"')
    a("  else")
    a('    ok "TOKEN_CREATE_FAILED:${UG}"')
    a("  fi")
    a("fi")
    a("")
    a("# ---- ACLs (idempotent: aclmod sets the triple) ----")
    a("acl_ensure() {")
    a('  local path="$1" role="$2"')
    a('  if pveum acl modify "$path" --tokens "$UG" --roles "$role" >/dev/null 2>&1; then')
    a('    ok "ACL_SET:${path}:${role}"')
    a("  else")
    a('    ok "ACL_FAILED:${path}:${role}"')
    a("  fi")
    a("}")
    a("")
    for path, role in spec.acls:
        a(f'acl_ensure {_sh(path)} {_sh(role)}')
    a("")
    a('ok "DONE"')
    return "\n".join(lines) + "\n"
